name: Python package

on:
  push:
    branches: ["feature"]
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      working-directory: 'compliance-status-checker'
      run: docker-compose up

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      working-directory: 'compliance-status-checker/backend'
      run: npm install

    - name: Run tests
      working-directory: 'compliance-status-checker/backend'
      run: npm run test
