name: Python package

on:
  push:
    branches: ["feature"]
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      working-directory: 'compliance-status-checker/backend'
      run: npm install

    - name: Run tests
      working-directory: 'compliance-status-checker/backend'
      run: npm test

    # - name: Start containers
    #   working-directory: 'compliance-status-checker'
    #   run: docker-compose up