name: Python package

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9 
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install flake8 pytest
          python -m pip install flake8 pydantic
          python -m pip install flake8 typer
      - name: Test with pytest
        run: python -m pytest
            
       
